# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://after-wordpress.netlify.com/'
baseurl: ''
title: 'After WordPress'
description: 'Where to go After WordPress'
permalink: pretty
logo: "https://www.gravatar.com/avatar/7a6778e090aa22bf10a848d313815cc9?s=52"

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/static/img/logo@16px.png'
  32: '/static/img/logo@32px.png'
  180: '/static/img/logo@180px.png'
  512: '/static/img/logo@512px.png'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Thoughts and ideas beyond WordPress"
    feature_text: |
      Welcome to After WordPress News
    feature_image: "https://picsum.photos/2560/600?image=744"
